### ISSUE TITLE
Serve static files

### ISSUE THREAD

**Issue by vslinko** [vslinko/webpack-amok-dev-server#2]
WebpackAmokDevServer doesn't serve static files itself.
I would like to add this feature because I don't wont to use external server in example.
WebpackAmokDevServer using `express` to serve webpack bundle, so we just need to configure `express.static` middleware.

This feature should be configurable and disabled by default.
To enable this feature user should set path to directory to `contentBase` configuration point.

**Comment by caspervonb** [comment]
What if amok-server was aware of buffers? Currently it supports aliasing to other files, but it could support aliasing to in memory buffers too.

**Comment by vslinko** [comment]
I like single responsibility principle. In my mind amok should handle only one problem — hot reloading.
