### ISSUE TITLE
Check out

### ISSUE THREAD

**Issue by vslinko** [vslinko/webpack-amok-dev-server#4]
@caspervonb messages from gitter:

> Once https://github.com/caspervonb/amok/pull/87 lands we should be at 1.0.0 stable (rolling out pre-releases now)
> Not breaking anything in amok's API but rdbg was pre 1.0, so @vslinko I'm sorry but your custom pipeline is broken 
> Had to get lower level transport events in in preperation for other protocol adapters later on.

**Comment by caspervonb** [comment]
Most of it is fairly minor, wanted to keep the `client` object close to the protocol, it's direct methods are for dealing with RPC like commands while still having higher level domain objects, basically what that means is that `inspector.setScriptSource` becomes `client.debugger.setScriptSource`

See https://github.com/caspervonb/amok/blob/upgrade/rdbg/lib/hotpatch.js for the refactored internals, grab me on bitter if you need assistance, and feel free to raise an issue on rdbg if there's something that feels missing from the surface API, i did remove getScripts, but i was only arguing with my self at the time if it was a good idea. rdbg will be following semver from today on as it's been marked 1.0.0 stable

**Comment by vslinko** [comment]
Thank you. I'll watch it later.
